# Generated by Django 4.0.6 on 2022-08-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t6_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
