# Generated by Django 4.0.6 on 2022-08-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t6_dashboard', '0002_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='point',
            new_name='points',
        ),
    ]
